import { defineConfig } from "tsup";

export default defineConfig({
    tsconfig: "tsconfig.build.json",
    entry: {
        index: "src/index.ts",
        core: "src/core.ts",
        "runtime-tools": "src/runtime-tools.ts",
        "runtime-admin": "src/runtime-admin.ts",
        selectors: "src/selectors-entry.ts",
        computed: "src/computed-entry.ts",
        helpers: "src/helpers.ts",
        server: "src/server.ts",
        async: "src/async.ts",
        persist: "src/persist.ts",
        sync: "src/sync.ts",
        devtools: "src/devtools.ts",
        feature: "src/feature.ts",
        install: "src/install.ts",
        react: "src/hooks.ts",
        testing: "src/testing.ts",
    },
    format: ["esm", "cjs"],
    experimentalDts: true,
    bundle: true,
    minify: true,
    treeshake: true,
    sourcemap: true,
    clean: true,
    splitting: false,
    drop: ["debugger"],
});
