import { defineConfig } from "tsup";

export default defineConfig({
    tsconfig: "tsconfig.build.json",
    entry: {
        index: "src/index.ts",
        core: "src/core/index.ts",
        "runtime-tools": "src/runtime-tools/index.ts",
        "runtime-admin": "src/runtime-admin/index.ts",
        selectors: "src/selectors/index.ts",
        computed: "src/computed/index.ts",
        helpers: "src/helpers/index.ts",
        server: "src/server/index.ts",
        async: "src/async.ts",
        persist: "src/persist.ts",
        sync: "src/sync.ts",
        devtools: "src/devtools/index.ts",
        feature: "src/feature.ts",
        install: "src/install.ts",
        testing: "src/helpers/testing.ts",
    },
    format: ["esm"],
    dts: { resolve: true },
    bundle: true,
    minify: true,
    treeshake: true,
    sourcemap: true,
    clean: true,
    splitting: false,
    drop: ["debugger"],
});
