name: Bug report
description: Tell us about something that is broken.
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened? Keep it concise.
      placeholder: e.g. "Docs sidebar collapses on mobile when scrolling"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List each step clearly.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / screenshots
      placeholder: What actually happened? Add screenshots if helpful.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: OS, browser, Node version, package version
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant console output or stack traces (if any).
